### PR TITLE
SPC-2792 - Preserve original formatting, but use some exceptions - list and quote

### PR DESCRIPTION
**Pull request by Krizai**
When pasting into list or quote we don't want to break them

### CODE REVIEW

**Review by foxinushka — DISMISSED** [review]

**Comment by Krizai** [comment]
retest please

**Comment by Krizai** [comment]
retest please

**Comment by Krizai** [comment]
retest please

**Comment by Krizai** [comment]
retest please

**Comment by Krizai** [comment]
retest please

**Comment by Krizai** [comment]
retest please

**Comment by Krizai** [comment]
retest please

**Review by Rastopyr — APPROVED** [review]

**Pull request merged**
